### PR TITLE
Repair arg_match failure

### PR DESCRIPTION
**Pull request by jonocarroll**
#914 introduced a check which appears to be too strict - on debug I see that the ordering of the values can be changed. This PR appears to resolve a lot of issues (related: https://github.com/r-lib/vctrs/issues/790) I've been seeing.

Fixes https://github.com/r-lib/vctrs/issues/790

### CODE REVIEW

**Comment by DavisVaughan** [comment]
I'm wondering if, rather than making `arg_match()` more flexible, we should have `tibble:::repaired_names()` call `arg_match()` first and then pass the result on to `vec_as_names()`.

https://github.com/tidyverse/tibble/blob/10a25b9a1447901b469364f39081bfa15a7f270e/R/repair-names.R#L7

The core problem here is that `tibble::tibble()` uses a different ordering of the inlined name repair values than `vec_as_names()` does, but then it relies on the `arg_match()` call in `vec_as_names()`, when I think it should really use its own

CC @krlmlr

**Comment by lionel-** [comment]
I tend to agree with @DavisVaughan. We had a similar problem in #914. @AliciaSchep and I concluded it's better to arg-match early.

We could always relax this later if needed. Worth noting that CRAN tibble doesn't use vctrs yet, so it won't be affected by the new `arg_match()` checks.

**Comment by lionel-** [comment]
I've now come around on this. I don't think there's much advantage to being this strict, and it does makes it harder to wrap around arg-matching functions with different defaults. The additional strictness doesn't seem worth the friction it brings, since users are unlikely to write typos or wrong arguments this way. So I'm inclined to merge this PR. What do you think @DavisVaughan?

**Comment by DavisVaughan** [comment]
That sounds fine!

**Comment by lionel-** [comment]
@jonocarroll Could you add a unit test for this please?

**Comment by jonocarroll** [comment]
Can do.

**Comment by jonocarroll** [comment]
I've altered the error message when `!setequal(arg, values)` to help indicate that this may be what is not happening.

Tests to cover both positive and negative cases.

**Comment by lionel-** [comment]
hmm I think it's better to leave the original error message. Mentioning the semantics for the default feels like a distraction that might confuse users.

**Comment by lionel-** [comment]
I have changed it so that it now mentions the valid possible strings.

**Comment by lionel-** [comment]
Thanks!

By the way I have squashed the PR. Since you've been developing from your `master` branch, this means the upstream master and your local master have now diverged. You can fix it by using `git fetch upstream && git reset --hard upstream/master` from your master branch (assuming the upstream rlang repo is called `upstream`).

**Comment by jonocarroll** [comment]
No worries. I'm not working on any `rlang` changes outside of this so I'll just burn down my fork :fire: but thank you.

**Pull request merged**
