### PR TITLE
Update `compat-` files to new naming scheme

### PR DESCRIPTION
**Pull request by hadley**

### CODE REVIEW

**Review by lionel- — APPROVED** [review]

**Review by jennybc — COMMENTED** [review]
This renaming needs to be tweaked for consistency (remove the `import-`):

```
R/compat-defer.R → R/import-standalone-defer.R
```

**Comment by hadley** [comment]
@jennybc doesn’t that file come from withr?

**Comment by jennybc** [comment]
OK I just did what I thought needed to be done. See what you think.

**Comment by jennybc** [comment]
The name of the file now matches what it claims its name to be.

**Comment by hadley** [comment]
Isn't https://github.com/r-lib/withr/blob/main/R/compat-defer.R the source of this content? Do I misunderstand?

**Comment by lionel-** [comment]
yup it is, defer is an import in rlang from withr.

**Comment by jennybc** [comment]
I see a file here named `import-standalone-defer.R`. **Note the `import-` prefix.**

I don't think any other standalone file is named that way? Nor is the original file in withr named that way.
And inside that file, it claims to come from an original name `standalone-defer.R`, also without `import-` prefix.

But I seem to be confused about what's going on here and will revert my commit.

**Comment by lionel-** [comment]
Source files are prefixed with `standalone-`, and imported files are prefixed with `import-standalone-`, this way you can tell by the name if a file is an original or a copycat.

**Review by DavisVaughan — APPROVED** [review]

**Pull request merged**
