### PR TITLE
Improve infix operator labelling

### PR DESCRIPTION
**Pull request by lionel-**
Closest #956.

Also exports `is_call_infix()`. I didn't end up using it though, because we're technically after the print type rather than the parse type here.

cc @hadley

### CODE REVIEW

**Comment by hadley** [comment]
Can you explain why? i.e. what function it makes a difference for?

**Comment by lionel-** [comment]
It doesn't make a big difference, only in artificial cases:

```r
is_call_infix(quote(`+`(1, 2)))
#> [1] TRUE
is_call_infix(quote(`+`(1, 2, 3)))
#> [1] TRUE

call_print_fine_type(quote(`+`(1, 2)))
#> [1] "infix"
call_print_fine_type(quote(`+`(1, 2, 3)))
#> [1] "call"
```

Still doesn't feel right though. Binary operators with multiple arguments are not really "infix". Maybe I should just unexport `is_call_infix()`.

**Comment by lionel-** [comment]
Or change it to:

```r
is_call_infix(quote(`+`(1)))
#> [1] FALSE
is_call_infix(quote(`+`(1, 2)))
#> [1] TRUE
is_call_infix(quote(`+`(1, 2, 3)))
#> [1] FALSE    # <- Used to be TRUE
```

**Comment by hadley** [comment]
Yeah, I like the last option — I think an infix operator must have two arguments. I'm also not 100% sure about the inclusion of special operators.

**Pull request merged**
