### PR TITLE
Fix typo in eval_tidy() doc

### PR DESCRIPTION
**Pull request by romainfrancois**
typo

### CODE REVIEW

**Comment by lionel-** [comment]
Could you redocument please.

**Comment by lionel-** [comment]
A better commit message would be "Fix typo in eval_tidy() doc"

**Comment by romainfrancois** [comment]
✔️ it was a lazy edit on github pr at first. I have edited the `Rd` file manually because `document()` wanted to update other files but not this one 🤷‍♂️.

**Comment by lionel-** [comment]
You probably have a different roxygen version than the one used for rlang?

You restored the typo in the `.R` file with that last commit ;)

**Comment by romainfrancois** [comment]
🤦‍♂️  alright, I'll make some ☕️ and try again

**Comment by lionel-** [comment]
Perfect thanks!

**Pull request merged**
