### PR TITLE
Autogenerate rlang version

### PR DESCRIPTION
**Pull request by krlmlr**
for checks between R package and DLL mismatch.

Are `grep` and `cut` available everywhere?

### CODE REVIEW

**Comment by lionel-** [comment]
I would prefer to try this in another package first to check if this is portable enough.

**Comment by krlmlr** [comment]
Fair enough, I'll link here.

**Comment by lionel-** [comment]
I think it would be better to do it automatically from the usethis helpers when there exists a `version.h` file in `src`.

**Comment by krlmlr** [comment]
I'm not sure, your call.

**Comment by krlmlr** [comment]
I'm not sure if this is the responsibility of a `./configure` script or of `Makevars`, it can work either way. Hard-coding the logic in an external helper adds a dependency that's hard to track.

**Comment by lionel-** [comment]
This is now handled by `usethis::use_version()` which updates version.c.

**Pull request closed without merging**
