### PR TITLE
Fix build and simulated interrupts on Windows

### PR DESCRIPTION
**Pull request by lionel-**
cc @mvkorpel

@kevinushey Is this a portable and safe way of simulating interrupts on Windows environments? Cf `r_interrupt()` in cnd.c.

### CODE REVIEW

**Comment by yutannihilation** [comment]
I found an old but similar issue on Rcpp, https://github.com/Rcpp11/attributes/issues/27. At that time, `<Rinterface.h>` has been replaced with `<R_ext/GraphicsEngine.h>`. Does this also the case with rlang?

https://github.com/Rcpp11/Rcpp11/commit/e66445f53409dac13c9af0cf73a481b1742fc716

(Sorry, I'm too poor to join the discussion, but I'm verrry curious about this issue because all of my attempts to `devtools::install(tidyverse/*)` keep failing on my Windows ... 😢 )

**Comment by lionel-** [comment]
Hmm I'm not sure why GraphicsEngine was included there. But from what I see they just throw a regular error rather than signal an interrupt. I think the approach in this PR is cleaner because the interrupt facilities (such as resume restarts) will be installed if available. cc @romainfrancois

**Comment by romainfrancois** [comment]
I have no memory of why I used `<R_ext/GraphicsEngine.h>`

**Comment by yutannihilation** [comment]
Ah, thanks for the explanation. I got it. Sorry for having interrupted you.

**Comment by lionel-** [comment]
@kevinushey I have merged to fix the build issues of ggplot2-devel users, but I'm still interested in any comments if you have time :)

**Comment by kevinushey** [comment]
Yep, this looks like the right thing to do!

**Comment by lionel-** [comment]
Great thanks!

**Pull request merged**
